import type { AudioAsset, AudioSpeaker } from "./types";

export const audioSpeakers = {
  female: {
    id: "speaker-female-yan",
    name: "阿欣",
    gender: "female",
    label: "女聲",
  },
  male: {
    id: "speaker-male-jun",
    name: "阿俊",
    gender: "male",
    label: "男聲",
  },
} as const satisfies Record<string, AudioSpeaker>;

const makeVariants = (pathStem: string) =>
  ({
    "100": `/audio/${pathStem}@100.mp3`,
    "75": `/audio/${pathStem}@75.mp3`,
    "50": `/audio/${pathStem}@50.mp3`,
  }) as const;

const female = audioSpeakers.female.id;
const male = audioSpeakers.male.id;

export const audioManifest = [
  {
    id: "audio-hello",
    speakerId: female,
    kind: "phrase",
    label: "你好",
    transcript: "你好",
    variants: makeVariants("speaker-female-yan/audio-hello"),
    glossaryIds: ["g-hello"],
  },
  {
    id: "audio-m4-goi1",
    speakerId: female,
    kind: "phrase",
    label: "唔該",
    transcript: "唔該",
    variants: makeVariants("speaker-female-yan/audio-m4-goi1"),
    glossaryIds: ["g-please-use"],
  },
  {
    id: "audio-thanks",
    speakerId: female,
    kind: "phrase",
    label: "多謝",
    transcript: "多謝",
    variants: makeVariants("speaker-female-yan/audio-thanks"),
    glossaryIds: ["g-thanks"],
  },
  {
    id: "audio-sorry",
    speakerId: female,
    kind: "phrase",
    label: "對唔住",
    transcript: "對唔住",
    variants: makeVariants("speaker-female-yan/audio-sorry"),
    glossaryIds: ["g-sorry"],
  },
  {
    id: "audio-bye",
    speakerId: female,
    kind: "phrase",
    label: "再見",
    transcript: "再見",
    variants: makeVariants("speaker-female-yan/audio-bye"),
    glossaryIds: ["g-bye"],
  },
  {
    id: "audio-one",
    speakerId: male,
    kind: "syllable",
    label: "一",
    transcript: "一",
    variants: makeVariants("speaker-male-jun/audio-one"),
    glossaryIds: ["g-one"],
  },
  {
    id: "audio-two",
    speakerId: male,
    kind: "syllable",
    label: "二",
    transcript: "二",
    variants: makeVariants("speaker-male-jun/audio-two"),
    glossaryIds: ["g-two"],
  },
  {
    id: "audio-three",
    speakerId: male,
    kind: "syllable",
    label: "三",
    transcript: "三",
    variants: makeVariants("speaker-male-jun/audio-three"),
    glossaryIds: ["g-three"],
  },
  {
    id: "audio-four",
    speakerId: male,
    kind: "syllable",
    label: "四",
    transcript: "四",
    variants: makeVariants("speaker-male-jun/audio-four"),
    glossaryIds: ["g-four"],
  },
  {
    id: "audio-five",
    speakerId: male,
    kind: "syllable",
    label: "五",
    transcript: "五",
    variants: makeVariants("speaker-male-jun/audio-five"),
    glossaryIds: ["g-five"],
  },
  {
    id: "audio-six",
    speakerId: male,
    kind: "syllable",
    label: "六",
    transcript: "六",
    variants: makeVariants("speaker-male-jun/audio-six"),
    glossaryIds: ["g-six"],
  },
  {
    id: "audio-seven",
    speakerId: male,
    kind: "syllable",
    label: "七",
    transcript: "七",
    variants: makeVariants("speaker-male-jun/audio-seven"),
    glossaryIds: ["g-seven"],
  },
  {
    id: "audio-eight",
    speakerId: male,
    kind: "syllable",
    label: "八",
    transcript: "八",
    variants: makeVariants("speaker-male-jun/audio-eight"),
    glossaryIds: ["g-eight"],
  },
  {
    id: "audio-nine",
    speakerId: male,
    kind: "syllable",
    label: "九",
    transcript: "九",
    variants: makeVariants("speaker-male-jun/audio-nine"),
    glossaryIds: ["g-nine"],
  },
  {
    id: "audio-ten",
    speakerId: male,
    kind: "syllable",
    label: "十",
    transcript: "十",
    variants: makeVariants("speaker-male-jun/audio-ten"),
    glossaryIds: ["g-ten"],
  },
  {
    id: "audio-m4",
    speakerId: female,
    kind: "syllable",
    label: "唔",
    transcript: "唔",
    variants: makeVariants("speaker-female-yan/audio-m4"),
    glossaryIds: ["g-dont"],
  },
  {
    id: "audio-hai6",
    speakerId: female,
    kind: "syllable",
    label: "係",
    transcript: "係",
    variants: makeVariants("speaker-female-yan/audio-hai6"),
    glossaryIds: ["g-to-be"],
  },
  {
    id: "audio-hai2",
    speakerId: female,
    kind: "syllable",
    label: "喺",
    transcript: "喺",
    variants: makeVariants("speaker-female-yan/audio-hai2"),
    glossaryIds: ["g-at"],
  },
  {
    id: "audio-zo2",
    speakerId: female,
    kind: "syllable",
    label: "咗",
    transcript: "咗",
    variants: makeVariants("speaker-female-yan/audio-zo2"),
    glossaryIds: ["g-past"],
  },
  {
    id: "audio-sin1",
    speakerId: female,
    kind: "syllable",
    label: "先",
    transcript: "先",
    variants: makeVariants("speaker-female-yan/audio-sin1"),
    glossaryIds: ["g-before"],
  },
  {
    id: "audio-bathroom",
    speakerId: female,
    kind: "phrase",
    label: "廁所",
    transcript: "廁所",
    variants: makeVariants("speaker-female-yan/audio-bathroom"),
    glossaryIds: ["g-bathroom"],
  },
  {
    id: "audio-washroom",
    speakerId: female,
    kind: "phrase",
    label: "洗手間",
    transcript: "洗手間",
    variants: makeVariants("speaker-female-yan/audio-washroom"),
    glossaryIds: ["g-restroom"],
  },
  {
    id: "audio-where",
    speakerId: female,
    kind: "phrase",
    label: "邊度",
    transcript: "邊度",
    variants: makeVariants("speaker-female-yan/audio-where"),
    glossaryIds: ["g-where"],
  },
  {
    id: "audio-please-ask",
    speakerId: female,
    kind: "phrase",
    label: "請問",
    transcript: "請問",
    variants: makeVariants("speaker-female-yan/audio-please-ask"),
    glossaryIds: ["g-please"],
  },
  {
    id: "audio-checkin",
    speakerId: male,
    kind: "phrase",
    label: "入住登記",
    transcript: "入住登記",
    variants: makeVariants("speaker-male-jun/audio-checkin"),
    glossaryIds: ["g-checkin"],
  },
  {
    id: "audio-document",
    speakerId: male,
    kind: "phrase",
    label: "證件",
    transcript: "證件",
    variants: makeVariants("speaker-male-jun/audio-document"),
    glossaryIds: ["g-document"],
  },
  {
    id: "audio-exit",
    speakerId: female,
    kind: "phrase",
    label: "出口",
    transcript: "出口",
    variants: makeVariants("speaker-female-yan/audio-exit"),
    glossaryIds: ["g-exit"],
  },
  {
    id: "audio-nei5",
    speakerId: female,
    kind: "syllable",
    label: "你",
    transcript: "你",
    variants: makeVariants("speaker-female-yan/audio-nei5"),
    glossaryIds: ["g-hello"],
  },
  {
    id: "audio-lei5",
    speakerId: female,
    kind: "syllable",
    label: "李",
    transcript: "李",
    variants: makeVariants("speaker-female-yan/audio-lei5"),
  },
  {
    id: "audio-negaa6",
    speakerId: female,
    kind: "phrase",
    label: "你呀",
    transcript: "你呀",
    variants: makeVariants("speaker-female-yan/audio-negaa6"),
    glossaryIds: ["g-hello"],
  },
  {
    id: "audio-tones-si1",
    speakerId: female,
    kind: "tone",
    label: "詩",
    transcript: "詩",
    variants: makeVariants("speaker-female-yan/audio-tones-si1"),
  },
  {
    id: "audio-tone-drill-si1",
    speakerId: female,
    kind: "tone",
    label: "si1",
    transcript: "si1",
    variants: makeVariants("speaker-female-yan/audio-tone-drill-si1"),
  },
  {
    id: "audio-dialogue-greet-1",
    speakerId: female,
    kind: "dialogue",
    label: "你好，請問入住登記喺邊度？",
    transcript: "你好，請問入住登記喺邊度？",
    variants: makeVariants("speaker-female-yan/audio-dialogue-greet-1"),
    glossaryIds: ["g-hello", "g-please", "g-checkin", "g-at", "g-where"],
  },
  {
    id: "audio-dialogue-greet-2",
    speakerId: male,
    kind: "dialogue",
    label: "喺前面右邊，請攞證件。",
    transcript: "喺前面右邊，請攞證件。",
    variants: makeVariants("speaker-male-jun/audio-dialogue-greet-2"),
    glossaryIds: ["g-at", "g-document"],
  },
  {
    id: "audio-dialogue-greet-3",
    speakerId: female,
    kind: "dialogue",
    label: "唔該。",
    transcript: "唔該。",
    variants: makeVariants("speaker-female-yan/audio-dialogue-greet-3"),
    glossaryIds: ["g-please-use"],
  },
  {
    id: "audio-dialogue-greet-4",
    speakerId: male,
    kind: "dialogue",
    label: "唔使客氣。",
    transcript: "唔使客氣。",
    variants: makeVariants("speaker-male-jun/audio-dialogue-greet-4"),
  },
] as const satisfies readonly AudioAsset[];

export type AudioId = (typeof audioManifest)[number]["id"];

export const audioById = audioManifest.reduce<Record<AudioId, AudioAsset>>((result, asset) => {
  result[asset.id] = asset;
  return result;
}, {} as Record<AudioId, AudioAsset>);
