import type { Lesson, Section, StepChoice, ToneNumber } from "./types";
import { audioSpeakers } from "./audio";

const toneChoices = [1, 2, 3, 4, 5, 6] as const satisfies readonly ToneNumber[];

const survivalChoices = [
  { id: "hello", label: "你好" },
  { id: "please", label: "唔該" },
  { id: "thanks", label: "多謝" },
  { id: "sorry", label: "對唔住" },
] as const satisfies readonly StepChoice[];

const numberOrderTiles = ["十", "七", "二", "八", "三", "一", "九", "五", "四", "六"] as const;
const numberOrderCorrect = ["一", "二", "三", "四", "五", "六", "七", "八", "九", "十"] as const;

const jyutpingChoices = [
  { id: "m4-goi1", label: "m4 goi1", jyutping: "m4 goi1" },
  { id: "m4-gwoi1", label: "m4 gwoi1", jyutping: "m4 gwoi1" },
  { id: "ng5-goi1", label: "ng5 goi1", jyutping: "ng5 goi1" },
] as const satisfies readonly StepChoice[];

const minimalPairChoices = [
  { id: "nei5", label: "你", jyutping: "nei5" },
  { id: "lei5", label: "李", jyutping: "lei5" },
  { id: "nei1", label: "呢", jyutping: "nei1" },
] as const satisfies readonly StepChoice[];

const whereChoices = [
  { id: "where", label: "邊度" },
  { id: "bathroom", label: "廁所" },
  { id: "exit", label: "出口" },
] as const satisfies readonly StepChoice[];

const signageChoices = [
  { id: "left", label: "左" },
  { id: "right", label: "右" },
  { id: "forward", label: "前" },
  { id: "back", label: "後" },
] as const satisfies readonly StepChoice[];

const checkpointGreetingChoices = [
  { id: "hello", label: "你好" },
  { id: "please", label: "唔該" },
  { id: "thanks", label: "多謝" },
] as const satisfies readonly StepChoice[];

const checkpointToneChoices = toneChoices;

const startHereLessons = [
  {
    id: "start-01-script-toggle",
    sectionId: "start-here",
    order: 1,
    title: "繁簡切換",
    subtitle: "先把顯示切順手",
    summary: "先找到繁簡切換，免得看字卡住。",
    displayMode: "both",
    estimatedMinutes: 2,
    objectives: ["知道全站可以切換繁簡", "知道學習時先聽再跟讀"],
    stepIds: ["start-01-script-toggle-quiz-1", "start-01-script-toggle-quiz-2"],
    steps: [
      {
        kind: "quizItem",
        id: "start-01-script-toggle-quiz-1",
        title: "快速確認",
        question: "如果你想把全站顯示切到簡體，最直接的做法係？",
        choices: [
          { id: "navbar", label: "按頂部的繁簡按鈕" },
          { id: "reload", label: "重新整理頁面" },
          { id: "search", label: "先去搜尋頁面" },
        ],
        correctChoiceId: "navbar",
        explanation: "繁簡切換是全站固定按鈕，之後學習內容也會一起轉。",
      },
      {
        kind: "quizItem",
        id: "start-01-script-toggle-quiz-2",
        title: "學法順序",
        question: "學新句子時，邊個順序最穩妥？",
        choices: [
          { id: "listen-first", label: "先聽，再跟讀" },
          { id: "read-only", label: "只看字面" },
          { id: "memorize", label: "直接硬背" },
        ],
        correctChoiceId: "listen-first",
        explanation: "先聽清，再開口，會穩得多。",
      },
    ],
  },
  {
    id: "start-02-survival-phrases",
    sectionId: "start-here",
    order: 2,
    title: "生存句",
    subtitle: "先拿最常用的幾句",
    summary: "你好、唔該、多謝、對唔住、再見。",
    displayMode: "both",
    estimatedMinutes: 3,
    objectives: ["認得高頻禮貌句", "分辨唔該與多謝"],
    stepIds: ["start-02-survival-listen-1", "start-02-survival-fill-1"],
    steps: [
      {
        kind: "listenAndChoose",
        id: "start-02-survival-listen-1",
        title: "聽到邊一句",
        prompt: "你聽到邊一句？",
        audioId: "audio-hello",
        choices: survivalChoices,
        correctChoiceId: "hello",
        explanation: "這是最穩妥的問候句。",
        glossaryIds: ["g-hello"],
      },
      {
        kind: "fillBlank",
        id: "start-02-survival-fill-1",
        title: "禮貌補空",
        prompt: "補出最自然的一句：",
        template: "___，借過。",
        wordBank: ["你好", "唔該", "多謝", "再見"],
        answer: "唔該",
        explanation: "叫人讓路、借過、請人幫忙，都可以用唔該。",
        glossaryIds: ["g-please-use"],
      },
    ],
  },
  {
    id: "start-03-numbers-1-10",
    sectionId: "start-here",
    order: 3,
    title: "數字一到十",
    subtitle: "先把號碼看懂",
    summary: "先把一到十排順，再對上字音。",
    displayMode: "both",
    estimatedMinutes: 4,
    objectives: ["認得一到十", "把六的讀音對上"],
    stepIds: ["start-03-numbers-reorder-1", "start-03-numbers-jyutping-1"],
    steps: [
      {
        kind: "reorderTiles",
        id: "start-03-numbers-reorder-1",
        title: "把順序排好",
        prompt: "請把 1 到 10 排好。",
        tiles: numberOrderTiles,
        correctOrder: numberOrderCorrect,
        explanation: "你只要順序對了，數字讀法之後再慢慢補也可以。",
        glossaryIds: ["g-one", "g-two", "g-three", "g-four", "g-five", "g-six", "g-seven", "g-eight", "g-nine", "g-ten"],
      },
      {
        kind: "chooseJyutping",
        id: "start-03-numbers-jyutping-1",
        title: "對上讀音",
        prompt: "「六」的粵拼係邊個？",
        targetText: "六",
        choices: [
          { id: "luk6", label: "luk6", jyutping: "luk6" },
          { id: "luk1", label: "luk1", jyutping: "luk1" },
          { id: "luk9", label: "luk9", jyutping: "luk9" },
        ],
        correctChoiceId: "luk6",
        explanation: "六讀 luk6，這個字在日期、價錢、號碼裡都很常見。",
        glossaryIds: ["g-six"],
      },
    ],
  },
  {
    id: "start-04-function-words",
    sectionId: "start-here",
    order: 4,
    title: "常用功能字",
    subtitle: "先抓最常見的幾個",
    summary: "唔、係、喺、咗、先。",
    displayMode: "both",
    estimatedMinutes: 3,
    objectives: ["認得高頻功能字", "分辨喺和唔"],
    stepIds: ["start-04-function-fill-1", "start-04-function-quiz-1"],
    steps: [
      {
        kind: "fillBlank",
        id: "start-04-function-fill-1",
        title: "補出否定詞",
        prompt: "補出最自然的一個字：",
        template: "我___去。",
        wordBank: ["唔", "係", "喺", "咗", "先"],
        answer: "唔",
        explanation: "唔最常用來做否定，先把它當成「不／別」去理解。",
        glossaryIds: ["g-dont"],
      },
      {
        kind: "quizItem",
        id: "start-04-function-quiz-1",
        title: "快速辨義",
        question: "「喺」最接近邊個意思？",
        choices: [
          { id: "at", label: "在／於" },
          { id: "not", label: "不／沒有" },
          { id: "finished", label: "了／完成" },
        ],
        correctChoiceId: "at",
        explanation: "喺是表示位置的核心字，句子裡很實用。",
        glossaryIds: ["g-at"],
      },
    ],
  },
] as const satisfies readonly Lesson[];

const soundLabLessons = [
  {
    id: "sound-01-jyutping-basics",
    sectionId: "sound-lab-1",
    order: 1,
    title: "粵拼入門",
    subtitle: "先把字音拆開",
    summary: "先把粵拼和字音對上。",
    displayMode: "both",
    estimatedMinutes: 4,
    objectives: ["看懂粵拼", "把字和音對上"],
    stepIds: ["sound-01-jyutping-input-1", "sound-01-jyutping-choose-1"],
    steps: [
      {
        kind: "jyutpingInput",
        id: "sound-01-jyutping-input-1",
        title: "直接輸入音節",
        prompt: "請輸入：你好",
        targetTokens: ["nei5", "hou2"],
        suggestions: [
          { token: "nei5", displayText: "你", jyutping: "nei5", glossaryIds: ["g-hello"] },
          { token: "hou2", displayText: "好", jyutping: "hou2" },
          { token: "m4 goi1", displayText: "唔該", jyutping: "m4 goi1", glossaryIds: ["g-please-use"] },
          { token: "syut1", displayText: "說", jyutping: "syut1" },
        ],
        phraseSuggestions: [
          { input: "nei5 hou2", displayText: "你好", note: "最常見問候" },
          { input: "m4 goi1", displayText: "唔該", note: "服務場景高頻" },
        ],
        explanation: "你可以把粵拼當成讀音提示，先打對音節，再看建議。",
      },
      {
        kind: "chooseJyutping",
        id: "sound-01-jyutping-choose-1",
        title: "對上唸法",
        prompt: "「唔該」的粵拼係邊個？",
        targetText: "唔該",
        choices: jyutpingChoices,
        correctChoiceId: "m4-goi1",
        explanation: "唔該讀 m4 goi1，這是你今天最值得先熟的服務句。",
        glossaryIds: ["g-please-use"],
      },
    ],
  },
  {
    id: "sound-02-six-tones",
    sectionId: "sound-lab-1",
    order: 2,
    title: "六聲",
    subtitle: "先把高低方向抓住",
    summary: "先把一二三四五六聲聽清。",
    displayMode: "audio-first",
    estimatedMinutes: 3,
    objectives: ["認識六聲", "把音高方向抓住"],
    stepIds: ["sound-02-six-tones-listen-1", "sound-02-six-tones-tone-1"],
    steps: [
      {
        kind: "listenAndChoose",
        id: "sound-02-six-tones-listen-1",
        title: "聽出例字",
        prompt: "你聽到邊個字？",
        audioId: "audio-tones-si1",
        choices: [
          { id: "si1", label: "詩" },
          { id: "si4", label: "時" },
          { id: "si6", label: "市" },
        ],
        correctChoiceId: "si1",
        explanation: "這裡先只要求你把高平聲聽熟。",
      },
      {
        kind: "chooseTone",
        id: "sound-02-six-tones-tone-1",
        title: "聲調判斷",
        prompt: "「詩」係邊個聲調？",
        syllable: "si",
        correctTone: 1,
        choices: checkpointToneChoices,
        explanation: "詩是第 1 聲，聲調先這樣記。",
        audioId: "audio-tones-si1",
      },
    ],
  },
  {
    id: "sound-03-tone-drill",
    sectionId: "sound-lab-1",
    order: 3,
    title: "聲調跟讀",
    subtitle: "把耳朵和嘴巴對起來",
    summary: "先跟讀一個最短音節，再聽一次自己和原音的差異。",
    displayMode: "audio-first",
    estimatedMinutes: 6,
    objectives: ["完成一次 repeat machine", "建立跟讀節奏", "把聲調練習變成習慣"],
    reviewTag: "tone",
    stepIds: ["sound-03-tone-repeat-1", "sound-03-tone-listen-1", "sound-03-tone-quiz-1"],
    steps: [
      {
        kind: "repeatMachine",
        id: "sound-03-tone-repeat-1",
        title: "跟讀最短格",
        prompt: "先聽，再跟讀，然後按自己感覺評分。",
        targetAudioId: "audio-tone-drill-si1",
        transcript: "si1",
        speakerId: audioSpeakers.female.id,
        selfRatingLabels: ["唔準", "可以", "幾準"],
        loopSuggested: true,
        reviewLaterSuggested: true,
        glossaryIds: [],
      },
      {
        kind: "listenAndChoose",
        id: "sound-03-tone-listen-1",
        title: "同一音節，聽邊個",
        prompt: "你聽到邊個？",
        audioId: "audio-tone-drill-si1",
        choices: [
          { id: "si1", label: "si1" },
          { id: "si2", label: "si2" },
          { id: "si4", label: "si4" },
        ],
        correctChoiceId: "si1",
        explanation: "先把高平音節穩住，之後再擴展其他聲調。",
      },
      {
        kind: "quizItem",
        id: "sound-03-tone-quiz-1",
        title: "今日習慣",
        question: "如果你對聲調未穩，最值得做邊樣？",
        choices: [
          { id: "listen-repeat", label: "先聽，再跟讀，再比對" },
          { id: "skip", label: "直接跳去背字" },
          { id: "write-only", label: "只看字面，不聽音" },
        ],
        correctChoiceId: "listen-repeat",
        explanation: "跟讀與比對是今天的重點，不是死背。",
      },
    ],
  },
  {
    id: "sound-04-minimal-pairs",
    sectionId: "sound-lab-1",
    order: 4,
    title: "你 / 李 對比",
    subtitle: "先分清 n 同 l",
    summary: "先把你 nei5 同李 lei5 分開。",
    displayMode: "audio-first",
    estimatedMinutes: 3,
    objectives: ["分辨 n 同 l", "認得你和李"],
    reviewTag: "n-l",
    stepIds: ["sound-04-minimal-listen-1", "sound-04-minimal-choose-1"],
    steps: [
      {
        kind: "listenAndChoose",
        id: "sound-04-minimal-listen-1",
        title: "聽聲母差別",
        prompt: "你聽到邊個字？",
        audioId: "audio-nei5",
        choices: minimalPairChoices,
        correctChoiceId: "nei5",
        explanation: "你是 nei5，不是 lei5。",
        glossaryIds: ["g-hello"],
      },
      {
        kind: "chooseJyutping",
        id: "sound-04-minimal-choose-1",
        title: "字和音對上",
        prompt: "「你」的粵拼係邊個？",
        targetText: "你",
        choices: [
          { id: "nei5", label: "nei5", jyutping: "nei5" },
          { id: "lei5", label: "lei5", jyutping: "lei5" },
          { id: "ni3", label: "ni3", jyutping: "ni3" },
        ],
        correctChoiceId: "nei5",
        explanation: "你讀 nei5，這是今天最重要的 n / l 對比之一。",
        glossaryIds: ["g-hello"],
      },
    ],
  },
] as const satisfies readonly Lesson[];

const meetAndGreetLessons = [
  {
    id: "meet-01-bathroom",
    sectionId: "meet-and-greet",
    order: 1,
    title: "洗手間喺邊度",
    subtitle: "先拿最實用的問路句",
    summary: "請問，廁所喺邊度？",
    displayMode: "both",
    estimatedMinutes: 3,
    objectives: ["會說問洗手間的句子", "把邊度和喺對上"],
    stepIds: ["meet-01-bathroom-fill-1", "meet-01-bathroom-listen-1"],
    steps: [
      {
        kind: "fillBlank",
        id: "meet-01-bathroom-fill-1",
        title: "補出位置字",
        prompt: "把句子補完整：",
        template: "請問，廁所___邊度？",
        wordBank: ["喺", "係", "咗", "先"],
        answer: "喺",
        explanation: "喺表示位置，所以這句一定是喺邊度。",
        glossaryIds: ["g-at", "g-where"],
      },
      {
        kind: "listenAndChoose",
        id: "meet-01-bathroom-listen-1",
        title: "聽到邊個字",
        prompt: "你聽到邊個詞？",
        audioId: "audio-where",
        choices: whereChoices,
        correctChoiceId: "where",
        explanation: "邊度是問位置最重要的字之一。",
        glossaryIds: ["g-where"],
      },
    ],
  },
  {
    id: "meet-02-mini-dialogue",
    sectionId: "meet-and-greet",
    order: 2,
    title: "前台對話",
    subtitle: "把問候和問路放進場景",
    summary: "你好，請問入住登記喺邊度？",
    displayMode: "audio-first",
    estimatedMinutes: 7,
    objectives: ["跟著一段短對話", "認得禮貌回應", "把入住登記和證件放進場景"],
    stepIds: ["meet-02-mini-dialogue-dialogue-1", "meet-02-mini-dialogue-quiz-1"],
    steps: [
      {
        kind: "dialogue",
        id: "meet-02-mini-dialogue-dialogue-1",
        title: "前台對話",
        prompt: "先看一遍，再聽一遍。",
        turns: [
          {
            speakerId: audioSpeakers.female.id,
            speakerLabel: "女聲",
            text: "你好，請問入住登記喺邊度？",
            audioId: "audio-dialogue-greet-1",
          },
          {
            speakerId: audioSpeakers.male.id,
            speakerLabel: "男聲",
            text: "喺前面右邊，請攞證件。",
            audioId: "audio-dialogue-greet-2",
          },
          {
            speakerId: audioSpeakers.female.id,
            speakerLabel: "女聲",
            text: "唔該。",
            audioId: "audio-dialogue-greet-3",
          },
          {
            speakerId: audioSpeakers.male.id,
            speakerLabel: "男聲",
            text: "唔使客氣。",
            audioId: "audio-dialogue-greet-4",
          },
        ],
        summary: "這段對話把禮貌問候、位置、證件和回應都放在一起。",
        glossaryIds: ["g-hello", "g-please", "g-checkin", "g-at", "g-document", "g-please-use"],
      },
      {
        kind: "quizItem",
        id: "meet-02-mini-dialogue-quiz-1",
        title: "理解回應",
        question: "「唔使客氣」最接近邊個意思？",
        choices: [
          { id: "no-thanks", label: "不用謝" },
          { id: "wait", label: "請稍等" },
          { id: "sorry", label: "對不起" },
        ],
        correctChoiceId: "no-thanks",
        explanation: "這句是很自然的回應，表示不用客氣。",
      },
    ],
  },
  {
    id: "meet-03-signage-reading",
    sectionId: "meet-and-greet",
    order: 3,
    title: "標示",
    subtitle: "先看公共場所常見字",
    summary: "洗手間、出口、向左。",
    displayMode: "both",
    estimatedMinutes: 5,
    objectives: ["會看洗手間與出口等標示", "能根據標示做簡單方向判斷", "把閱讀變成即時實用能力"],
    stepIds: ["meet-03-signage-card-1", "meet-03-signage-quiz-1"],
    steps: [
      {
        kind: "signageReading",
        id: "meet-03-signage-card-1",
        title: "公共標示",
        signText: "洗手間\n向左",
        prompt: "如果你要去洗手間，應該點行？",
        choices: signageChoices,
        correctChoiceId: "left",
        explanation: "見到向左，就代表左邊方向。",
        glossaryIds: ["g-restroom"],
      },
      {
        kind: "quizItem",
        id: "meet-03-signage-quiz-1",
        title: "出口意思",
        question: "「出口」最接近邊個意思？",
        choices: [
          { id: "leave", label: "離開的方向" },
          { id: "toilet", label: "洗手間" },
          { id: "queue", label: "排隊位置" },
        ],
        correctChoiceId: "leave",
        explanation: "出口就是離開的位置或方向，很多車站和商場都會見到。",
        glossaryIds: ["g-exit"],
      },
    ],
  },
] as const satisfies readonly Lesson[];

const checkpointLessons = [
  {
    id: "a1-01-checkpoint-quiz",
    sectionId: "a1-checkpoint",
    order: 1,
    title: "入門小測",
    subtitle: "把前面內容串起來",
    summary: "問候、數字、聲調、問路。",
    displayMode: "both",
    estimatedMinutes: 7,
    objectives: ["快速回想問候句", "回想數字和聲調", "確認實用問路句"],
    reviewTag: "checkpoint-a1",
    stepIds: [
      "a1-01-checkpoint-quiz-1",
      "a1-01-checkpoint-quiz-2",
      "a1-01-checkpoint-quiz-3",
      "a1-01-checkpoint-quiz-4",
      "a1-01-checkpoint-quiz-5",
    ],
    steps: [
      {
        kind: "quizItem",
        id: "a1-01-checkpoint-quiz-1",
        title: "先認問候",
        question: "你聽到邊一句？",
        choices: checkpointGreetingChoices,
        correctChoiceId: "hello",
        explanation: "你好是最基本的問候句，先穩住它。",
      },
      {
        kind: "chooseJyutping",
        id: "a1-01-checkpoint-quiz-2",
        title: "數字回想",
        prompt: "「六」的粵拼係邊個？",
        targetText: "六",
        choices: [
          { id: "luk6", label: "luk6", jyutping: "luk6" },
          { id: "luk1", label: "luk1", jyutping: "luk1" },
          { id: "luk9", label: "luk9", jyutping: "luk9" },
        ],
        correctChoiceId: "luk6",
        explanation: "六是 luk6，這是今天很值得穩住的一個字。",
        glossaryIds: ["g-six"],
      },
      {
        kind: "chooseTone",
        id: "a1-01-checkpoint-quiz-3",
        title: "聲調確認",
        prompt: "「詩」係邊個聲調？",
        syllable: "si",
        correctTone: 1,
        choices: checkpointToneChoices,
        explanation: "第 1 聲先記住，高平音最常拿來做基準。",
        audioId: "audio-tones-si1",
      },
      {
        kind: "fillBlank",
        id: "a1-01-checkpoint-quiz-4",
        title: "問路補空",
        prompt: "補出最自然的一句：",
        template: "請問，廁所___邊度？",
        wordBank: ["喺", "係", "咗", "先"],
        answer: "喺",
        explanation: "喺表示位置，這句是問洗手間最穩妥的句子之一。",
        glossaryIds: ["g-at", "g-bathroom", "g-where"],
      },
      {
        kind: "listenAndChoose",
        id: "a1-01-checkpoint-quiz-5",
        title: "聽字辨音",
        prompt: "你聽到邊個字？",
        audioId: "audio-nei5",
        choices: minimalPairChoices,
        correctChoiceId: "nei5",
        explanation: "你是 nei5，這組對比很重要。",
        glossaryIds: ["g-hello"],
      },
    ],
  },
] as const satisfies readonly Lesson[];

export const curriculumLessons = [
  ...startHereLessons,
  ...soundLabLessons,
  ...meetAndGreetLessons,
  ...checkpointLessons,
] as const satisfies readonly Lesson[];

export const curriculumSections = [
  {
    id: "start-here",
    order: 1,
    title: "起步",
    subtitle: "先把字形、問候、數字熱身",
    summary: "繁簡切換、生存句、數字、功能字。",
    lessonIds: ["start-01-script-toggle", "start-02-survival-phrases", "start-03-numbers-1-10", "start-04-function-words"],
  },
  {
    id: "sound-lab-1",
    order: 2,
    title: "聲音一",
    subtitle: "先把粵拼與六聲建立起來",
    summary: "粵拼、六聲、跟讀、你李對比。",
    lessonIds: ["sound-01-jyutping-basics", "sound-02-six-tones", "sound-03-tone-drill", "sound-04-minimal-pairs"],
  },
  {
    id: "meet-and-greet",
    order: 3,
    title: "見面",
    subtitle: "把問路、對話、標示串成實景",
    summary: "洗手間、前台對話、公共標示。",
    lessonIds: ["meet-01-bathroom", "meet-02-mini-dialogue", "meet-03-signage-reading"],
  },
  {
    id: "a1-checkpoint",
    order: 4,
    title: "入門小測",
    subtitle: "用小測確認能否往前",
    summary: "把前面內容快速跑一遍。",
    lessonIds: ["a1-01-checkpoint-quiz"],
    checkpointLessonId: "a1-01-checkpoint-quiz",
  },
] as const satisfies readonly Section[];
