import type { Lesson, Section, StepChoice, ToneNumber } from "./types";
import { audioSpeakers } from "./audio";

const toneChoices = [1, 2, 3, 4, 5, 6] as const satisfies readonly ToneNumber[];

const survivalChoices = [
  { id: "hello", label: "你好" },
  { id: "please", label: "唔該" },
  { id: "thanks", label: "多謝" },
  { id: "sorry", label: "對唔住" },
] as const satisfies readonly StepChoice[];

const numberOrderTiles = ["十", "七", "二", "八", "三", "一", "九", "五", "四", "六"] as const;
const numberOrderCorrect = ["一", "二", "三", "四", "五", "六", "七", "八", "九", "十"] as const;

const jyutpingChoices = [
  { id: "m4-goi1", label: "m4 goi1", jyutping: "m4 goi1" },
  { id: "m4-gwoi1", label: "m4 gwoi1", jyutping: "m4 gwoi1" },
  { id: "ng5-goi1", label: "ng5 goi1", jyutping: "ng5 goi1" },
] as const satisfies readonly StepChoice[];

const minimalPairChoices = [
  { id: "nei5", label: "你", jyutping: "nei5" },
  { id: "lei5", label: "李", jyutping: "lei5" },
  { id: "nei1", label: "呢", jyutping: "nei1" },
] as const satisfies readonly StepChoice[];

const haiContrastChoices = [
  { id: "hai6", label: "係", jyutping: "hai6" },
  { id: "hai2", label: "喺", jyutping: "hai2" },
  { id: "sin1", label: "先", jyutping: "sin1" },
] as const satisfies readonly StepChoice[];

const functionCharacterChoices = [
  { id: "m4", label: "唔", jyutping: "m4" },
  { id: "zo2", label: "咗", jyutping: "zo2" },
  { id: "sin1", label: "先", jyutping: "sin1" },
] as const satisfies readonly StepChoice[];

const whereChoices = [
  { id: "where", label: "邊度" },
  { id: "bathroom", label: "廁所" },
  { id: "exit", label: "出口" },
] as const satisfies readonly StepChoice[];

const signageChoices = [
  { id: "left", label: "左" },
  { id: "right", label: "右" },
  { id: "forward", label: "前" },
  { id: "back", label: "後" },
] as const satisfies readonly StepChoice[];

const checkpointGreetingChoices = [
  { id: "tone", label: "聲調號碼" },
  { id: "order", label: "字的順序編號" },
  { id: "length", label: "把音拉長或縮短" },
] as const satisfies readonly StepChoice[];

const checkpointToneChoices = toneChoices;

const startHereLessons = [
  {
    id: "start-01-script-toggle",
    sectionId: "start-here",
    order: 1,
    title: "粵拼入口",
    subtitle: "先睇懂字形同調號",
    summary: "先會切字形，再知道數字係調號。",
    displayMode: "both",
    estimatedMinutes: 3,
    objectives: ["知道全站可以切換繁簡", "知道粵拼尾數是聲調號碼", "知道學習時先聽再跟讀"],
    stepIds: ["start-01-script-toggle-quiz-1", "start-01-script-toggle-quiz-2", "start-01-script-toggle-tone-1"],
    steps: [
      {
        kind: "quizItem",
        id: "start-01-script-toggle-quiz-1",
        title: "快速確認",
        question: "如果你想把全站顯示切到簡體，最直接的做法係？",
        choices: [
          { id: "navbar", label: "按頂部的繁簡按鈕" },
          { id: "reload", label: "重新整理頁面" },
          { id: "search", label: "先去搜尋頁面" },
        ],
        correctChoiceId: "navbar",
        explanation: "繁簡切換是全站固定按鈕，之後學習內容也會一起轉。",
      },
      {
        kind: "quizItem",
        id: "start-01-script-toggle-quiz-2",
        title: "調號先認",
        question: "粵拼像「nei5 hou2」後面的數字，最接近邊個作用？",
        choices: [
          { id: "tone", label: "聲調號碼" },
          { id: "order", label: "字的順序編號" },
          { id: "length", label: "把音拉長或縮短" },
        ],
        correctChoiceId: "tone",
        explanation: "粵拼後面的數字是聲調，先把這個系統看懂，之後認字音會快很多。",
      },
      {
        kind: "chooseTone",
        id: "start-01-script-toggle-tone-1",
        title: "先認尾數",
        prompt: "如果寫成「nei5」，尾數應該揀邊個調號？",
        syllable: "nei",
        correctTone: 5,
        choices: checkpointToneChoices,
        explanation: "先把「尾數 = 聲調」這個規則記住，不用一開始背完整理論。",
      },
    ],
  },
  {
    id: "start-02-survival-phrases",
    sectionId: "start-here",
    order: 2,
    title: "高頻字 1",
    subtitle: "先把最常見字對上音",
    summary: "先把你、好同你好對上讀音。",
    displayMode: "both",
    estimatedMinutes: 3,
    objectives: ["認得你同好的讀音", "用粵拼打出你好"],
    stepIds: ["start-02-survival-jyutping-1", "start-02-survival-input-1"],
    steps: [
      {
        kind: "chooseJyutping",
        id: "start-02-survival-jyutping-1",
        title: "對上讀音",
        prompt: "「好」的粵拼係邊個？",
        targetText: "好",
        choices: [
          { id: "hou2", label: "hou2", jyutping: "hou2" },
          { id: "hou3", label: "hou3", jyutping: "hou3" },
          { id: "hok3", label: "hok3", jyutping: "hok3" },
        ],
        correctChoiceId: "hou2",
        explanation: "先把高頻單字同粵拼直接對上，不用急著背整句。",
      },
      {
        kind: "jyutpingInput",
        id: "start-02-survival-input-1",
        title: "直接輸入",
        prompt: "請輸入：你好",
        targetTokens: ["nei5", "hou2"],
        suggestions: [
          { token: "nei5", displayText: "你", jyutping: "nei5" },
          { token: "hou2", displayText: "好", jyutping: "hou2" },
          { token: "ngo5", displayText: "我", jyutping: "ngo5" },
          { token: "m4", displayText: "唔", jyutping: "m4", glossaryIds: ["g-dont"] },
          { token: "hai6", displayText: "係", jyutping: "hai6", glossaryIds: ["g-to-be"] },
        ],
        phraseSuggestions: [
          { input: "nei5 hou2", displayText: "你好", note: "先把字同音節對齊" },
        ],
        explanation: "高頻字先打熟，之後再慢慢擴到更多詞和句。",
      },
    ],
  },
  {
    id: "start-03-numbers-1-10",
    sectionId: "start-here",
    order: 3,
    title: "高頻字 2",
    subtitle: "先分清係同喺",
    summary: "兩個常見字音近，但意思完全唔同。",
    displayMode: "both",
    estimatedMinutes: 4,
    objectives: ["聽得出係同喺", "把係 hai6 同喺 hai2 對上"],
    stepIds: ["start-03-numbers-listen-1", "start-03-numbers-jyutping-1"],
    steps: [
      {
        kind: "listenAndChoose",
        id: "start-03-numbers-listen-1",
        title: "先聽差別",
        prompt: "你聽到邊個字？",
        audioId: "audio-hai2",
        choices: haiContrastChoices,
        correctChoiceId: "hai2",
        explanation: "喺 hai2 表示位置；先把音同字分開記。",
        glossaryIds: ["g-at", "g-to-be"],
      },
      {
        kind: "chooseJyutping",
        id: "start-03-numbers-jyutping-1",
        title: "再對上讀音",
        prompt: "「係」的粵拼係邊個？",
        targetText: "係",
        choices: [
          { id: "hai6", label: "hai6", jyutping: "hai6" },
          { id: "hai2", label: "hai2", jyutping: "hai2" },
          { id: "hei6", label: "hei6", jyutping: "hei6" },
        ],
        correctChoiceId: "hai6",
        explanation: "係 hai6、喺 hai2，只差一個調號，但用途差很遠。",
        glossaryIds: ["g-to-be", "g-at"],
      },
    ],
  },
  {
    id: "start-04-function-words",
    sectionId: "start-here",
    order: 4,
    title: "高頻字 3",
    subtitle: "再抓三個超高頻口語字",
    summary: "唔、咗、先對音，再慢慢放入句子。",
    displayMode: "both",
    estimatedMinutes: 3,
    objectives: ["認得唔 m4", "認得先 sin1 同咗 zo2"],
    stepIds: ["start-04-function-listen-1", "start-04-function-quiz-1"],
    steps: [
      {
        kind: "listenAndChoose",
        id: "start-04-function-listen-1",
        title: "先聽常用字",
        prompt: "你聽到邊個字？",
        audioId: "audio-m4",
        choices: functionCharacterChoices,
        correctChoiceId: "m4",
        explanation: "唔 m4 是非常高頻的口語字，先把聲音釘牢。",
        glossaryIds: ["g-dont", "g-past", "g-before"],
      },
      {
        kind: "chooseJyutping",
        id: "start-04-function-quiz-1",
        title: "再對上拼法",
        prompt: "「先」的粵拼係邊個？",
        targetText: "先",
        choices: [
          { id: "sin1", label: "sin1", jyutping: "sin1" },
          { id: "sin2", label: "sin2", jyutping: "sin2" },
          { id: "saan1", label: "saan1", jyutping: "saan1" },
        ],
        correctChoiceId: "sin1",
        explanation: "先 sin1 在口語裡很常見，先記字音，句法之後再慢慢展開。",
        glossaryIds: ["g-before"],
      },
    ],
  },
] as const satisfies readonly Lesson[];

const soundLabLessons = [
  {
    id: "sound-01-jyutping-basics",
    sectionId: "sound-lab-1",
    order: 1,
    title: "粵拼 1",
    subtitle: "用輸入把字音記住",
    summary: "先用高頻字練拼寫。",
    displayMode: "both",
    estimatedMinutes: 4,
    objectives: ["把我係寫成粵拼", "記住唔 m4"],
    stepIds: ["sound-01-jyutping-input-1", "sound-01-jyutping-choose-1"],
    steps: [
      {
        kind: "jyutpingInput",
        id: "sound-01-jyutping-input-1",
        title: "直接輸入音節",
        prompt: "請輸入：我係",
        targetTokens: ["ngo5", "hai6"],
        suggestions: [
          { token: "ngo5", displayText: "我", jyutping: "ngo5" },
          { token: "hai6", displayText: "係", jyutping: "hai6", glossaryIds: ["g-to-be"] },
          { token: "hai2", displayText: "喺", jyutping: "hai2", glossaryIds: ["g-at"] },
          { token: "m4", displayText: "唔", jyutping: "m4", glossaryIds: ["g-dont"] },
          { token: "nei5", displayText: "你", jyutping: "nei5" },
        ],
        phraseSuggestions: [
          { input: "ngo5 hai6", displayText: "我係", note: "先把高頻字串起來" },
        ],
        explanation: "先把高頻字逐個拼對，粵拼會慢慢變成你記字音的主系統。",
      },
      {
        kind: "chooseJyutping",
        id: "sound-01-jyutping-choose-1",
        title: "對上唸法",
        prompt: "「唔」的粵拼係邊個？",
        targetText: "唔",
        choices: [
          { id: "m4", label: "m4", jyutping: "m4" },
          { id: "m6", label: "m6", jyutping: "m6" },
          { id: "ng4", label: "ng4", jyutping: "ng4" },
        ],
        correctChoiceId: "m4",
        explanation: "唔 m4 很高頻，先把這類單字音節背熟，之後句子會輕鬆很多。",
        glossaryIds: ["g-dont"],
      },
    ],
  },
  {
    id: "sound-02-six-tones",
    sectionId: "sound-lab-1",
    order: 2,
    title: "聲調 1",
    subtitle: "先把調號和高低對齊",
    summary: "數字唔係裝飾，係聲調。",
    displayMode: "audio-first",
    estimatedMinutes: 3,
    objectives: ["認識六聲", "把音高方向抓住"],
    stepIds: ["sound-02-six-tones-listen-1", "sound-02-six-tones-tone-1"],
    steps: [
      {
        kind: "listenAndChoose",
        id: "sound-02-six-tones-listen-1",
        title: "聽出例字",
        prompt: "你聽到邊個字？",
        audioId: "audio-tones-si1",
        choices: [
          { id: "si1", label: "詩" },
          { id: "si4", label: "時" },
          { id: "si6", label: "市" },
        ],
        correctChoiceId: "si1",
        explanation: "這裡先只要求你把高平聲聽熟。",
      },
      {
        kind: "chooseTone",
        id: "sound-02-six-tones-tone-1",
        title: "聲調判斷",
        prompt: "「詩」係邊個聲調？",
        syllable: "si",
        correctTone: 1,
        choices: checkpointToneChoices,
        explanation: "詩是第 1 聲，聲調先這樣記。",
        audioId: "audio-tones-si1",
      },
    ],
  },
  {
    id: "sound-03-tone-drill",
    sectionId: "sound-lab-1",
    order: 3,
    title: "跟讀 1",
    subtitle: "先練最短音節",
    summary: "先聽、錄、比對，再跟一次。",
    displayMode: "audio-first",
    estimatedMinutes: 6,
    objectives: ["完成一次 repeat machine", "建立跟讀節奏", "把聲調練習變成習慣"],
    reviewTag: "tone",
    stepIds: ["sound-03-tone-repeat-1", "sound-03-tone-listen-1", "sound-03-tone-quiz-1"],
    steps: [
      {
        kind: "repeatMachine",
        id: "sound-03-tone-repeat-1",
        title: "跟讀最短格",
        prompt: "先聽，再跟讀，然後按自己感覺評分。",
        targetAudioId: "audio-tone-drill-si1",
        transcript: "si1",
        speakerId: audioSpeakers.female.id,
        selfRatingLabels: ["唔準", "可以", "幾準"],
        loopSuggested: true,
        reviewLaterSuggested: true,
        glossaryIds: [],
      },
      {
        kind: "listenAndChoose",
        id: "sound-03-tone-listen-1",
        title: "同一音節，聽邊個",
        prompt: "你聽到邊個？",
        audioId: "audio-tone-drill-si1",
        choices: [
          { id: "si1", label: "si1" },
          { id: "si2", label: "si2" },
          { id: "si4", label: "si4" },
        ],
        correctChoiceId: "si1",
        explanation: "先把高平音節穩住，之後再擴展其他聲調。",
      },
      {
        kind: "quizItem",
        id: "sound-03-tone-quiz-1",
        title: "今日習慣",
        question: "如果你對聲調未穩，最值得做邊樣？",
        choices: [
          { id: "listen-repeat", label: "先聽，再跟讀，再比對" },
          { id: "skip", label: "直接跳去背字" },
          { id: "write-only", label: "只看字面，不聽音" },
        ],
        correctChoiceId: "listen-repeat",
        explanation: "跟讀與比對是今天的重點，不是死背。",
      },
    ],
  },
  {
    id: "sound-04-minimal-pairs",
    sectionId: "sound-lab-1",
    order: 4,
    title: "聲母對比 1",
    subtitle: "先穩住 n 同 l",
    summary: "普通話相近，粵語要分清。",
    displayMode: "audio-first",
    estimatedMinutes: 3,
    objectives: ["分辨 n 同 l", "認得你和李"],
    reviewTag: "n-l",
    stepIds: ["sound-04-minimal-listen-1", "sound-04-minimal-choose-1"],
    steps: [
      {
        kind: "listenAndChoose",
        id: "sound-04-minimal-listen-1",
        title: "聽聲母差別",
        prompt: "你聽到邊個字？",
        audioId: "audio-nei5",
        choices: minimalPairChoices,
        correctChoiceId: "nei5",
        explanation: "你是 nei5，不是 lei5。",
        glossaryIds: ["g-hello"],
      },
      {
        kind: "chooseJyutping",
        id: "sound-04-minimal-choose-1",
        title: "字和音對上",
        prompt: "「你」的粵拼係邊個？",
        targetText: "你",
        choices: [
          { id: "nei5", label: "nei5", jyutping: "nei5" },
          { id: "lei5", label: "lei5", jyutping: "lei5" },
          { id: "ni3", label: "ni3", jyutping: "ni3" },
        ],
        correctChoiceId: "nei5",
        explanation: "你讀 nei5，這是今天最重要的 n / l 對比之一。",
        glossaryIds: ["g-hello"],
      },
    ],
  },
] as const satisfies readonly Lesson[];

const meetAndGreetLessons = [
  {
    id: "meet-01-bathroom",
    sectionId: "meet-and-greet",
    order: 1,
    title: "問路 1",
    subtitle: "位置詞先配上地點詞",
    summary: "喺同邊度先落地。",
    displayMode: "both",
    estimatedMinutes: 3,
    objectives: ["會說問洗手間的句子", "把邊度和喺對上"],
    stepIds: ["meet-01-bathroom-fill-1", "meet-01-bathroom-listen-1"],
    steps: [
      {
        kind: "fillBlank",
        id: "meet-01-bathroom-fill-1",
        title: "補出位置字",
        prompt: "把句子補完整：",
        template: "請問，廁所___邊度？",
        wordBank: ["喺", "係", "咗", "先"],
        answer: "喺",
        explanation: "喺表示位置，所以這句一定是喺邊度。",
        glossaryIds: ["g-at", "g-where"],
      },
      {
        kind: "listenAndChoose",
        id: "meet-01-bathroom-listen-1",
        title: "聽到邊個字",
        prompt: "你聽到邊個詞？",
        audioId: "audio-where",
        choices: whereChoices,
        correctChoiceId: "where",
        explanation: "邊度是問位置最重要的字之一。",
        glossaryIds: ["g-where"],
      },
    ],
  },
  {
    id: "meet-02-mini-dialogue",
    sectionId: "meet-and-greet",
    order: 2,
    title: "對話 1",
    subtitle: "把高頻字放進前台場景",
    summary: "短對話先聽懂，再回應。",
    displayMode: "audio-first",
    estimatedMinutes: 7,
    objectives: ["跟著一段短對話", "認得禮貌回應", "把入住登記和證件放進場景"],
    stepIds: ["meet-02-mini-dialogue-dialogue-1", "meet-02-mini-dialogue-quiz-1"],
    steps: [
      {
        kind: "dialogue",
        id: "meet-02-mini-dialogue-dialogue-1",
        title: "前台對話",
        prompt: "先看一遍，再聽一遍。",
        turns: [
          {
            speakerId: audioSpeakers.female.id,
            speakerLabel: "女聲",
            text: "你好，請問入住登記喺邊度？",
            audioId: "audio-dialogue-greet-1",
          },
          {
            speakerId: audioSpeakers.male.id,
            speakerLabel: "男聲",
            text: "喺前面右邊，請攞證件。",
            audioId: "audio-dialogue-greet-2",
          },
          {
            speakerId: audioSpeakers.female.id,
            speakerLabel: "女聲",
            text: "唔該。",
            audioId: "audio-dialogue-greet-3",
          },
          {
            speakerId: audioSpeakers.male.id,
            speakerLabel: "男聲",
            text: "唔使客氣。",
            audioId: "audio-dialogue-greet-4",
          },
        ],
        summary: "這段對話把禮貌問候、位置、證件和回應都放在一起。",
        glossaryIds: ["g-hello", "g-please", "g-checkin", "g-at", "g-document", "g-please-use"],
      },
      {
        kind: "quizItem",
        id: "meet-02-mini-dialogue-quiz-1",
        title: "理解回應",
        question: "「唔使客氣」最接近邊個意思？",
        choices: [
          { id: "no-thanks", label: "不用謝" },
          { id: "wait", label: "請稍等" },
          { id: "sorry", label: "對不起" },
        ],
        correctChoiceId: "no-thanks",
        explanation: "這句是很自然的回應，表示不用客氣。",
      },
    ],
  },
  {
    id: "meet-03-signage-reading",
    sectionId: "meet-and-greet",
    order: 3,
    title: "標示 1",
    subtitle: "先看公共場所常見字",
    summary: "把位置同場所字一起看。",
    displayMode: "both",
    estimatedMinutes: 5,
    objectives: ["會看洗手間與出口等標示", "能根據標示做簡單方向判斷", "把閱讀變成即時實用能力"],
    stepIds: ["meet-03-signage-card-1", "meet-03-signage-quiz-1"],
    steps: [
      {
        kind: "signageReading",
        id: "meet-03-signage-card-1",
        title: "公共標示",
        signText: "洗手間\n向左",
        prompt: "如果你要去洗手間，應該點行？",
        choices: signageChoices,
        correctChoiceId: "left",
        explanation: "見到向左，就代表左邊方向。",
        glossaryIds: ["g-restroom"],
      },
      {
        kind: "quizItem",
        id: "meet-03-signage-quiz-1",
        title: "出口意思",
        question: "「出口」最接近邊個意思？",
        choices: [
          { id: "leave", label: "離開的方向" },
          { id: "toilet", label: "洗手間" },
          { id: "queue", label: "排隊位置" },
        ],
        correctChoiceId: "leave",
        explanation: "出口就是離開的位置或方向，很多車站和商場都會見到。",
        glossaryIds: ["g-exit"],
      },
    ],
  },
] as const satisfies readonly Lesson[];

const checkpointLessons = [
  {
    id: "a1-01-checkpoint-quiz",
    sectionId: "a1-checkpoint",
    order: 1,
    title: "入門小測",
    subtitle: "先測粵拼同高頻字",
    summary: "粵拼、高頻字、聲調、問路。",
    displayMode: "both",
    estimatedMinutes: 7,
    objectives: ["快速回想粵拼規則", "確認高頻字讀音", "確認實用問路句"],
    reviewTag: "checkpoint-a1",
    stepIds: [
      "a1-01-checkpoint-quiz-1",
      "a1-01-checkpoint-quiz-2",
      "a1-01-checkpoint-quiz-3",
      "a1-01-checkpoint-quiz-4",
      "a1-01-checkpoint-quiz-5",
    ],
    steps: [
      {
        kind: "quizItem",
        id: "a1-01-checkpoint-quiz-1",
        title: "先認系統",
        question: "粵拼像「nei5 hou2」後面的數字，最接近邊個作用？",
        choices: checkpointGreetingChoices,
        correctChoiceId: "tone",
        explanation: "先記住「數字 = 聲調」這件事，之後遇到大量字音才有系統。",
      },
      {
        kind: "chooseJyutping",
        id: "a1-01-checkpoint-quiz-2",
        title: "高頻字回想",
        prompt: "「喺」的粵拼係邊個？",
        targetText: "喺",
        choices: [
          { id: "hai2", label: "hai2", jyutping: "hai2" },
          { id: "hai6", label: "hai6", jyutping: "hai6" },
          { id: "hoi2", label: "hoi2", jyutping: "hoi2" },
        ],
        correctChoiceId: "hai2",
        explanation: "喺 hai2 很常見，而且和係 hai6 很容易混，所以值得反覆回想。",
        glossaryIds: ["g-at", "g-to-be"],
      },
      {
        kind: "chooseTone",
        id: "a1-01-checkpoint-quiz-3",
        title: "聲調確認",
        prompt: "「詩」係邊個聲調？",
        syllable: "si",
        correctTone: 1,
        choices: checkpointToneChoices,
        explanation: "第 1 聲先記住，高平音最常拿來做基準。",
        audioId: "audio-tones-si1",
      },
      {
        kind: "fillBlank",
        id: "a1-01-checkpoint-quiz-4",
        title: "問路補空",
        prompt: "補出最自然的一句：",
        template: "請問，廁所___邊度？",
        wordBank: ["喺", "係", "咗", "先"],
        answer: "喺",
        explanation: "喺表示位置，這句是問洗手間最穩妥的句子之一。",
        glossaryIds: ["g-at", "g-bathroom", "g-where"],
      },
      {
        kind: "listenAndChoose",
        id: "a1-01-checkpoint-quiz-5",
        title: "聽字辨音",
        prompt: "你聽到邊個字？",
        audioId: "audio-nei5",
        choices: minimalPairChoices,
        correctChoiceId: "nei5",
        explanation: "你是 nei5，這組對比很重要。",
        glossaryIds: ["g-hello"],
      },
    ],
  },
] as const satisfies readonly Lesson[];

export const curriculumLessons = [
  ...startHereLessons,
  ...soundLabLessons,
  ...meetAndGreetLessons,
  ...checkpointLessons,
] as const satisfies readonly Lesson[];

export const curriculumSections = [
  {
    id: "start-here",
    order: 1,
    title: "起步",
    subtitle: "先把粵拼、高頻字同調號抓穩",
    summary: "繁簡切換、粵拼格式、高頻字。",
    lessonIds: ["start-01-script-toggle", "start-02-survival-phrases", "start-03-numbers-1-10", "start-04-function-words"],
  },
  {
    id: "sound-lab-1",
    order: 2,
    title: "聲音一",
    subtitle: "用跟讀、聲調同聲母對比練耳朵",
    summary: "粵拼輸入、聲調、跟讀、n / l 對比。",
    lessonIds: ["sound-01-jyutping-basics", "sound-02-six-tones", "sound-03-tone-drill", "sound-04-minimal-pairs"],
  },
  {
    id: "meet-and-greet",
    order: 3,
    title: "實景",
    subtitle: "把字音放回可用場景",
    summary: "問路、前台對話、公共標示。",
    lessonIds: ["meet-01-bathroom", "meet-02-mini-dialogue", "meet-03-signage-reading"],
  },
  {
    id: "a1-checkpoint",
    order: 4,
    title: "入門小測",
    subtitle: "用小測確認能否往前",
    summary: "把前面內容快速跑一遍。",
    lessonIds: ["a1-01-checkpoint-quiz"],
    checkpointLessonId: "a1-01-checkpoint-quiz",
  },
] as const satisfies readonly Section[];
