import type { Lesson, Section, StepChoice, ToneNumber } from "./types";
import { audioSpeakers } from "./audio";

const toneChoices = [1, 2, 3, 4, 5, 6] as const satisfies readonly ToneNumber[];

const survivalChoices = [
  { id: "hello", label: "你好" },
  { id: "please", label: "唔該" },
  { id: "thanks", label: "多謝" },
  { id: "sorry", label: "對唔住" },
] as const satisfies readonly StepChoice[];

const numberOrderTiles = ["十", "七", "二", "八", "三", "一", "九", "五", "四", "六"] as const;
const numberOrderCorrect = ["一", "二", "三", "四", "五", "六", "七", "八", "九", "十"] as const;

const jyutpingChoices = [
  { id: "m4-goi1", label: "m4 goi1", jyutping: "m4 goi1" },
  { id: "m4-gwoi1", label: "m4 gwoi1", jyutping: "m4 gwoi1" },
  { id: "ng5-goi1", label: "ng5 goi1", jyutping: "ng5 goi1" },
] as const satisfies readonly StepChoice[];

const minimalPairChoices = [
  { id: "nei5", label: "你", jyutping: "nei5" },
  { id: "lei5", label: "李", jyutping: "lei5" },
  { id: "nei1", label: "呢", jyutping: "nei1" },
] as const satisfies readonly StepChoice[];

const whereChoices = [
  { id: "where", label: "邊度" },
  { id: "bathroom", label: "廁所" },
  { id: "exit", label: "出口" },
] as const satisfies readonly StepChoice[];

const signageChoices = [
  { id: "left", label: "左" },
  { id: "right", label: "右" },
  { id: "forward", label: "前" },
  { id: "back", label: "後" },
] as const satisfies readonly StepChoice[];

const checkpointGreetingChoices = [
  { id: "hello", label: "你好" },
  { id: "please", label: "唔該" },
  { id: "thanks", label: "多謝" },
] as const satisfies readonly StepChoice[];

const checkpointToneChoices = toneChoices;

const startHereLessons = [
  {
    id: "start-01-script-toggle",
    sectionId: "start-here",
    order: 1,
    title: "先把字型調好",
    subtitle: "認識繁簡切換",
    summary: "先把顯示字型調順，後面看字才不會卡住。",
    displayMode: "both",
    estimatedMinutes: 4,
    objectives: ["知道全站可以切換繁簡", "先建立今天的學法", "熟悉最基本的操作節奏"],
    stepIds: ["start-01-script-toggle-card-1", "start-01-script-toggle-card-2", "start-01-script-toggle-quiz-1"],
    steps: [
      {
        kind: "learnCard",
        id: "start-01-script-toggle-card-1",
        title: "繁體先行",
        front: {
          heading: "先看繁體",
          body: "本課程先用繁體中文寫內容。你可以在介面上隨時切換成簡體，顯示會一起變。",
        },
        back: {
          heading: "為什麼先這樣做",
          body: "作者只寫一份內容，系統負責顯示轉換。意思不變，字型才是可切換的。",
          bullets: ["課文會跟著變字型", "Jyutping 與數字不受影響", "不在輸入框時可按 ` 鍵切換"],
        },
      },
      {
        kind: "learnCard",
        id: "start-01-script-toggle-card-2",
        title: "今天的學法",
        front: {
          heading: "先看字，再聽音",
          body: "先抓住意思，再看 Jyutping，最後再跟讀。你已經懂普通話，這一步會比零基礎更快。",
        },
        back: {
          heading: "今天只做三件事",
          body: "先懂句子在講什麼，再把聲音聽清楚，最後再出聲。",
          bullets: ["先抓住意思", "再聽聲調", "最後跟讀一次"],
        },
      },
      {
        kind: "quizItem",
        id: "start-01-script-toggle-quiz-1",
        title: "快速確認",
        question: "如果你想把全站顯示切到簡體，最直接的做法係？",
        choices: [
          { id: "navbar", label: "按頂部的繁簡按鈕" },
          { id: "reload", label: "重新整理頁面" },
          { id: "search", label: "先去搜尋頁面" },
        ],
        correctChoiceId: "navbar",
        explanation: "繁簡切換是全站固定按鈕，之後學習內容也會一起轉。",
      },
    ],
  },
  {
    id: "start-02-survival-phrases",
    sectionId: "start-here",
    order: 2,
    title: "第一批生存句",
    subtitle: "先把最常用的禮貌句背熟",
    summary: "先記五句最有用的日常起手式，立刻能用。",
    displayMode: "both",
    estimatedMinutes: 5,
    objectives: ["認得五句高頻生存句", "分辨唔該與多謝的場景", "用最短句子開口"],
    stepIds: ["start-02-survival-card-1", "start-02-survival-listen-1", "start-02-survival-fill-1"],
    steps: [
      {
        kind: "learnCard",
        id: "start-02-survival-card-1",
        title: "五句先行",
        front: {
          heading: "先背這五句",
          body: "你好、唔該、多謝、對唔住、再見。這五句會在旅程裡一直出現。",
        },
        back: {
          heading: "先分清用法",
          body: "你不用一次記很多字，只要先抓住場景：問候、請人幫忙、感謝、道歉、離開。",
          bullets: ["你好：見面問候", "唔該：麻煩／請／謝謝（服務場景）", "多謝：收到幫助或禮物後致謝", "對唔住：道歉", "再見：告別"],
        },
        glossaryIds: ["g-hello", "g-please-use", "g-thanks", "g-sorry", "g-bye"],
        audioIds: ["audio-hello", "audio-m4-goi1", "audio-thanks", "audio-sorry", "audio-bye"],
      },
      {
        kind: "listenAndChoose",
        id: "start-02-survival-listen-1",
        title: "聽到邊一句",
        prompt: "你聽到邊一句？",
        audioId: "audio-hello",
        choices: survivalChoices,
        correctChoiceId: "hello",
        explanation: "這是最穩妥的問候句。",
        glossaryIds: ["g-hello"],
      },
      {
        kind: "fillBlank",
        id: "start-02-survival-fill-1",
        title: "禮貌補空",
        prompt: "補出最自然的一句：",
        template: "___，借過。",
        wordBank: ["你好", "唔該", "多謝", "再見"],
        answer: "唔該",
        explanation: "叫人讓路、借過、請人幫忙，都可以用唔該。",
        glossaryIds: ["g-please-use"],
      },
    ],
  },
  {
    id: "start-03-numbers-1-10",
    sectionId: "start-here",
    order: 3,
    title: "數字 1 到 10",
    subtitle: "先把價格與房號看懂",
    summary: "數字是最早能拿來實戰的內容，今天先完成 1 到 10。",
    displayMode: "both",
    estimatedMinutes: 6,
    objectives: ["認得 1 到 10 的字與讀音", "能把數字順序排好", "把六這類高頻字音對上"],
    stepIds: ["start-03-numbers-card-1", "start-03-numbers-reorder-1", "start-03-numbers-jyutping-1"],
    steps: [
      {
        kind: "learnCard",
        id: "start-03-numbers-card-1",
        title: "1 到 10",
        front: {
          heading: "先看一遍",
          body: "一 jat1、二 ji6、三 saam1、四 sei3、五 ng5、六 luk6、七 cat1、八 baat3、九 gau2、十 sap6。",
        },
        back: {
          heading: "先不求背完",
          body: "你先認得大概長相和聲音，之後在價格、樓層、排隊號碼裡會一直見到。",
          bullets: ["一到五最先常見", "六、八、十在價格和編號裡很實用", "先會看，再會說"],
        },
        glossaryIds: ["g-one", "g-two", "g-three", "g-four", "g-five", "g-six", "g-seven", "g-eight", "g-nine", "g-ten"],
        audioIds: ["audio-one", "audio-two", "audio-three", "audio-four", "audio-five", "audio-six", "audio-seven", "audio-eight", "audio-nine", "audio-ten"],
      },
      {
        kind: "reorderTiles",
        id: "start-03-numbers-reorder-1",
        title: "把順序排好",
        prompt: "請把 1 到 10 排好。",
        tiles: numberOrderTiles,
        correctOrder: numberOrderCorrect,
        explanation: "你只要順序對了，數字讀法之後再慢慢補也可以。",
        glossaryIds: ["g-one", "g-two", "g-three", "g-four", "g-five", "g-six", "g-seven", "g-eight", "g-nine", "g-ten"],
      },
      {
        kind: "chooseJyutping",
        id: "start-03-numbers-jyutping-1",
        title: "對上讀音",
        prompt: "「六」的 Jyutping 係邊個？",
        targetText: "六",
        choices: [
          { id: "luk6", label: "luk6", jyutping: "luk6" },
          { id: "luk1", label: "luk1", jyutping: "luk1" },
          { id: "luk9", label: "luk9", jyutping: "luk9" },
        ],
        correctChoiceId: "luk6",
        explanation: "六讀 luk6，這個字在日期、價錢、號碼裡都很常見。",
        glossaryIds: ["g-six"],
      },
    ],
  },
  {
    id: "start-04-function-words",
    sectionId: "start-here",
    order: 4,
    title: "五個高值功能字",
    subtitle: "先把最常動的字抓穩",
    summary: "先學五個會不停出現的功能字，之後句子會突然變好懂。",
    displayMode: "both",
    estimatedMinutes: 5,
    objectives: ["認得五個高頻功能字", "分辨位置、否定、完成、順序", "開始讀到短句骨架"],
    stepIds: ["start-04-function-card-1", "start-04-function-fill-1", "start-04-function-quiz-1"],
    steps: [
      {
        kind: "learnCard",
        id: "start-04-function-card-1",
        title: "五個常見字",
        front: {
          heading: "先記骨架",
          body: "唔、係、喺、咗、先。這五個字在口語裡非常高頻，句子裡的作用也很大。",
        },
        back: {
          heading: "各自做什麼",
          body: "唔是否定；係是判斷；喺是位置；咗是完成；先是順序或條件。",
          bullets: ["唔：不", "係：是", "喺：在", "咗：了／已經完成", "先：先做某事"],
        },
        glossaryIds: ["g-dont", "g-to-be", "g-at", "g-past", "g-before"],
        audioIds: ["audio-m4", "audio-hai6", "audio-hai2", "audio-zo2", "audio-sin1"],
      },
      {
        kind: "fillBlank",
        id: "start-04-function-fill-1",
        title: "補出否定詞",
        prompt: "補出最自然的一個字：",
        template: "我___去。",
        wordBank: ["唔", "係", "喺", "咗", "先"],
        answer: "唔",
        explanation: "唔最常用來做否定，先把它當成「不／別」去理解。",
        glossaryIds: ["g-dont"],
      },
      {
        kind: "quizItem",
        id: "start-04-function-quiz-1",
        title: "快速辨義",
        question: "「喺」最接近邊個意思？",
        choices: [
          { id: "at", label: "在／於" },
          { id: "not", label: "不／沒有" },
          { id: "finished", label: "了／完成" },
        ],
        correctChoiceId: "at",
        explanation: "喺是表示位置的核心字，句子裡很實用。",
        glossaryIds: ["g-at"],
      },
    ],
  },
] as const satisfies readonly Lesson[];

const soundLabLessons = [
  {
    id: "sound-01-jyutping-basics",
    sectionId: "sound-lab-1",
    order: 1,
    title: "Jyutping 入門",
    subtitle: "先把字音拆開看",
    summary: "先理解 Jyutping 的用途，再看聲母、韻母和聲調。",
    displayMode: "both",
    estimatedMinutes: 6,
    objectives: ["知道 Jyutping 是什麼", "看懂 tone number", "把字和音先對上"],
    stepIds: ["sound-01-jyutping-card-1", "sound-01-jyutping-input-1", "sound-01-jyutping-choose-1"],
    steps: [
      {
        kind: "learnCard",
        id: "sound-01-jyutping-card-1",
        title: "Jyutping 是什麼",
        front: {
          heading: "先把音寫清楚",
          body: "Jyutping 會把聲母、韻母和聲調一起寫出來，例如 nei5 hou2、m4 goi1、syut1。",
        },
        back: {
          heading: "今天先記三件事",
          body: "你不用一次背完整表，先抓住它是「把 Cantonese 的聲音寫出來」的工具。",
          bullets: ["數字代表聲調", "字母代表音節骨架", "先從熟句子開始"],
        },
        glossaryIds: ["g-hello", "g-please-use"],
        audioIds: ["audio-hello", "audio-m4-goi1"],
      },
      {
        kind: "jyutpingInput",
        id: "sound-01-jyutping-input-1",
        title: "直接輸入音節",
        prompt: "請輸入：你好",
        targetTokens: ["nei5", "hou2"],
        suggestions: [
          { token: "nei5", displayText: "你", jyutping: "nei5", glossaryIds: ["g-hello"] },
          { token: "hou2", displayText: "好", jyutping: "hou2" },
          { token: "m4 goi1", displayText: "唔該", jyutping: "m4 goi1", glossaryIds: ["g-please-use"] },
          { token: "syut1", displayText: "說", jyutping: "syut1" },
        ],
        phraseSuggestions: [
          { input: "nei5 hou2", displayText: "你好", note: "最常見問候" },
          { input: "m4 goi1", displayText: "唔該", note: "服務場景高頻" },
        ],
        explanation: "你可以把 Jyutping 當成輸入式拼音，先打對音節，再看系統建議。",
      },
      {
        kind: "chooseJyutping",
        id: "sound-01-jyutping-choose-1",
        title: "對上唸法",
        prompt: "「唔該」的 Jyutping 係邊個？",
        targetText: "唔該",
        choices: jyutpingChoices,
        correctChoiceId: "m4-goi1",
        explanation: "唔該讀 m4 goi1，這是你今天最值得先熟的服務句。",
        glossaryIds: ["g-please-use"],
      },
    ],
  },
  {
    id: "sound-02-six-tones",
    sectionId: "sound-lab-1",
    order: 2,
    title: "六聲總覽",
    subtitle: "先建立聲調地圖",
    summary: "用六聲把 Cantonese 的聲音先放進腦中，之後才容易聽出差異。",
    displayMode: "audio-first",
    estimatedMinutes: 6,
    objectives: ["認識六聲", "知道 checked tone 的位置", "把音高方向先抓住"],
    stepIds: ["sound-02-six-tones-card-1", "sound-02-six-tones-listen-1", "sound-02-six-tones-tone-1"],
    steps: [
      {
        kind: "learnCard",
        id: "sound-02-six-tones-card-1",
        title: "六聲地圖",
        front: {
          heading: "先理解大方向",
          body: "廣州口語常用六聲。先不用追求樂譜一樣準，只要先知道高、中、低、升、平、降的方向。",
        },
        back: {
          heading: "六聲簡表",
          body: "1 高平、2 高升、3 中平、4 低降、5 低升、6 低平。入聲字會短促收尾，但先用六聲框架理解就夠。",
          bullets: ["先抓方向，不先死背圖", "聽多了，耳朵會慢慢對準", "入聲字先當短促收尾處理"],
        },
      },
      {
        kind: "listenAndChoose",
        id: "sound-02-six-tones-listen-1",
        title: "聽出例字",
        prompt: "你聽到邊個字？",
        audioId: "audio-tones-si1",
        choices: [
          { id: "si1", label: "詩" },
          { id: "si4", label: "時" },
          { id: "si6", label: "市" },
        ],
        correctChoiceId: "si1",
        explanation: "這裡先只要求你把高平聲聽熟。",
      },
      {
        kind: "chooseTone",
        id: "sound-02-six-tones-tone-1",
        title: "聲調判斷",
        prompt: "「詩」係邊個聲調？",
        syllable: "si",
        correctTone: 1,
        choices: checkpointToneChoices,
        explanation: "詩是第 1 聲，聲調先這樣記。",
        audioId: "audio-tones-si1",
      },
    ],
  },
  {
    id: "sound-03-tone-drill",
    sectionId: "sound-lab-1",
    order: 3,
    title: "聲調跟讀",
    subtitle: "把耳朵和嘴巴對起來",
    summary: "先跟讀一個最短音節，再聽一次自己和原音的差異。",
    displayMode: "audio-first",
    estimatedMinutes: 6,
    objectives: ["完成一次 repeat machine", "建立跟讀節奏", "把聲調練習變成習慣"],
    reviewTag: "tone",
    stepIds: ["sound-03-tone-repeat-1", "sound-03-tone-listen-1", "sound-03-tone-quiz-1"],
    steps: [
      {
        kind: "repeatMachine",
        id: "sound-03-tone-repeat-1",
        title: "跟讀最短格",
        prompt: "先聽，再跟讀，然後按自己感覺評分。",
        targetAudioId: "audio-tone-drill-si1",
        transcript: "si1",
        speakerId: audioSpeakers.female.id,
        selfRatingLabels: ["唔準", "可以", "幾準"],
        loopSuggested: true,
        reviewLaterSuggested: true,
        glossaryIds: [],
      },
      {
        kind: "listenAndChoose",
        id: "sound-03-tone-listen-1",
        title: "同一音節，聽邊個",
        prompt: "你聽到邊個？",
        audioId: "audio-tone-drill-si1",
        choices: [
          { id: "si1", label: "si1" },
          { id: "si2", label: "si2" },
          { id: "si4", label: "si4" },
        ],
        correctChoiceId: "si1",
        explanation: "先把高平音節穩住，之後再擴展其他聲調。",
      },
      {
        kind: "quizItem",
        id: "sound-03-tone-quiz-1",
        title: "今日習慣",
        question: "如果你對聲調未穩，最值得做邊樣？",
        choices: [
          { id: "listen-repeat", label: "先聽，再跟讀，再比對" },
          { id: "skip", label: "直接跳去背字" },
          { id: "write-only", label: "只看字面，不聽音" },
        ],
        correctChoiceId: "listen-repeat",
        explanation: "跟讀與比對是今天的重點，不是死背。",
      },
    ],
  },
  {
    id: "sound-04-minimal-pairs",
    sectionId: "sound-lab-1",
    order: 4,
    title: "n / l 最小對比",
    subtitle: "先把容易混的聲母分清",
    summary: "普通話母語者常把 n / l 混掉，這一課先把它們切開。",
    displayMode: "audio-first",
    estimatedMinutes: 5,
    objectives: ["分辨 n / l", "認得你 nei5 和李 lei5 的差別", "用聽覺先分辨再跟讀"],
    reviewTag: "n-l",
    stepIds: ["sound-04-minimal-card-1", "sound-04-minimal-listen-1", "sound-04-minimal-choose-1"],
    steps: [
      {
        kind: "learnCard",
        id: "sound-04-minimal-card-1",
        title: "先保住 n / l",
        front: {
          heading: "一個很重要的差別",
          body: "你 nei5 和李 lei5 只差聲母，這是普通話母語者很值得早點拉開的地方。",
        },
        back: {
          heading: "今天怎麼練",
          body: "先聽，確認嘴型和舌頭位置，再跟讀，不要只看字形。",
          bullets: ["n 和 l 不是同一個音", "先聽原音，再自己說", "同時把聲調也一起保住"],
        },
        glossaryIds: ["g-hello"],
        audioIds: ["audio-nei5", "audio-lei5"],
      },
      {
        kind: "listenAndChoose",
        id: "sound-04-minimal-listen-1",
        title: "聽聲母差別",
        prompt: "你聽到邊個字？",
        audioId: "audio-nei5",
        choices: minimalPairChoices,
        correctChoiceId: "nei5",
        explanation: "你是 nei5，不是 lei5。",
        glossaryIds: ["g-hello"],
      },
      {
        kind: "chooseJyutping",
        id: "sound-04-minimal-choose-1",
        title: "字和音對上",
        prompt: "「你」的 Jyutping 係邊個？",
        targetText: "你",
        choices: [
          { id: "nei5", label: "nei5", jyutping: "nei5" },
          { id: "lei5", label: "lei5", jyutping: "lei5" },
          { id: "ni3", label: "ni3", jyutping: "ni3" },
        ],
        correctChoiceId: "nei5",
        explanation: "你讀 nei5，這是今天最重要的 n / l 對比之一。",
        glossaryIds: ["g-hello"],
      },
    ],
  },
] as const satisfies readonly Lesson[];

const meetAndGreetLessons = [
  {
    id: "meet-01-bathroom",
    sectionId: "meet-and-greet",
    order: 1,
    title: "問洗手間",
    subtitle: "先把最實用的問路句練起來",
    summary: "先學一句最穩妥的問法，遇到實景可以立刻用。",
    displayMode: "both",
    estimatedMinutes: 6,
    objectives: ["會說問洗手間的句子", "能把邊度和喺對上", "先聽懂禮貌開頭"],
    stepIds: ["meet-01-bathroom-card-1", "meet-01-bathroom-fill-1", "meet-01-bathroom-listen-1"],
    steps: [
      {
        kind: "learnCard",
        id: "meet-01-bathroom-card-1",
        title: "問路的基本句",
        front: {
          heading: "最實用的一句",
          body: "請問，廁所喺邊度？這句幾乎可以直接拿去用。",
        },
        back: {
          heading: "句子骨架",
          body: "請問先開口，廁所是目的地，喺邊度就是位置。你只要把這三段認清就行。",
          bullets: ["請問：先禮貌開場", "廁所：實際目的地", "喺邊度：在哪裡"],
        },
        glossaryIds: ["g-please", "g-bathroom", "g-at", "g-where"],
        audioIds: ["audio-please-ask", "audio-bathroom", "audio-hai2", "audio-where"],
      },
      {
        kind: "fillBlank",
        id: "meet-01-bathroom-fill-1",
        title: "補出位置字",
        prompt: "把句子補完整：",
        template: "請問，廁所___邊度？",
        wordBank: ["喺", "係", "咗", "先"],
        answer: "喺",
        explanation: "喺表示位置，所以這句一定是喺邊度。",
        glossaryIds: ["g-at", "g-where"],
      },
      {
        kind: "listenAndChoose",
        id: "meet-01-bathroom-listen-1",
        title: "聽到邊個字",
        prompt: "你聽到邊個詞？",
        audioId: "audio-where",
        choices: whereChoices,
        correctChoiceId: "where",
        explanation: "邊度是問位置最重要的字之一。",
        glossaryIds: ["g-where"],
      },
    ],
  },
  {
    id: "meet-02-mini-dialogue",
    sectionId: "meet-and-greet",
    order: 2,
    title: "酒店前台迷你對話",
    subtitle: "把問候、問路、證件放進一段話",
    summary: "用一段很短的酒店對話，把今天前面學過的詞串起來。",
    displayMode: "audio-first",
    estimatedMinutes: 7,
    objectives: ["跟著一段短對話", "認得禮貌回應", "把入住登記和證件放進場景"],
    stepIds: ["meet-02-mini-dialogue-dialogue-1", "meet-02-mini-dialogue-quiz-1"],
    steps: [
      {
        kind: "dialogue",
        id: "meet-02-mini-dialogue-dialogue-1",
        title: "前台對話",
        prompt: "先看一遍，再聽一遍。",
        turns: [
          {
            speakerId: audioSpeakers.female.id,
            speakerLabel: "女聲",
            text: "你好，請問入住登記喺邊度？",
            audioId: "audio-dialogue-greet-1",
          },
          {
            speakerId: audioSpeakers.male.id,
            speakerLabel: "男聲",
            text: "喺前面右邊，請攞證件。",
            audioId: "audio-dialogue-greet-2",
          },
          {
            speakerId: audioSpeakers.female.id,
            speakerLabel: "女聲",
            text: "唔該。",
            audioId: "audio-dialogue-greet-3",
          },
          {
            speakerId: audioSpeakers.male.id,
            speakerLabel: "男聲",
            text: "唔使客氣。",
            audioId: "audio-dialogue-greet-4",
          },
        ],
        summary: "這段對話把禮貌問候、位置、證件和回應都放在一起。",
        glossaryIds: ["g-hello", "g-please", "g-checkin", "g-at", "g-document", "g-please-use"],
      },
      {
        kind: "quizItem",
        id: "meet-02-mini-dialogue-quiz-1",
        title: "理解回應",
        question: "「唔使客氣」最接近邊個意思？",
        choices: [
          { id: "no-thanks", label: "不用謝" },
          { id: "wait", label: "請稍等" },
          { id: "sorry", label: "對不起" },
        ],
        correctChoiceId: "no-thanks",
        explanation: "這句是很自然的回應，表示不用客氣。",
      },
    ],
  },
  {
    id: "meet-03-signage-reading",
    sectionId: "meet-and-greet",
    order: 3,
    title: "讀懂簡單標示",
    subtitle: "先看公共場所常見文字",
    summary: "先學會讀幾個最常見的公共標示，出門時會非常實際。",
    displayMode: "both",
    estimatedMinutes: 5,
    objectives: ["會看洗手間與出口等標示", "能根據標示做簡單方向判斷", "把閱讀變成即時實用能力"],
    stepIds: ["meet-03-signage-card-1", "meet-03-signage-quiz-1"],
    steps: [
      {
        kind: "signageReading",
        id: "meet-03-signage-card-1",
        title: "公共標示",
        signText: "洗手間\n向左",
        prompt: "如果你要去洗手間，應該點行？",
        choices: signageChoices,
        correctChoiceId: "left",
        explanation: "見到向左，就代表左邊方向。",
        glossaryIds: ["g-restroom"],
      },
      {
        kind: "quizItem",
        id: "meet-03-signage-quiz-1",
        title: "出口意思",
        question: "「出口」最接近邊個意思？",
        choices: [
          { id: "leave", label: "離開的方向" },
          { id: "toilet", label: "洗手間" },
          { id: "queue", label: "排隊位置" },
        ],
        correctChoiceId: "leave",
        explanation: "出口就是離開的位置或方向，很多車站和商場都會見到。",
        glossaryIds: ["g-exit"],
      },
    ],
  },
] as const satisfies readonly Lesson[];

const checkpointLessons = [
  {
    id: "a1-01-checkpoint-quiz",
    sectionId: "a1-checkpoint",
    order: 1,
    title: "A1 小測驗",
    subtitle: "把前面學過的東西串起來",
    summary: "用一份小測驗檢查你現在能不能穩定認字、認音、認場景。",
    displayMode: "both",
    estimatedMinutes: 7,
    objectives: ["快速回想問候句", "回想數字和聲調", "確認實用問路句"],
    reviewTag: "checkpoint-a1",
    stepIds: [
      "a1-01-checkpoint-quiz-1",
      "a1-01-checkpoint-quiz-2",
      "a1-01-checkpoint-quiz-3",
      "a1-01-checkpoint-quiz-4",
      "a1-01-checkpoint-quiz-5",
    ],
    steps: [
      {
        kind: "quizItem",
        id: "a1-01-checkpoint-quiz-1",
        title: "先認問候",
        question: "你聽到邊一句？",
        choices: checkpointGreetingChoices,
        correctChoiceId: "hello",
        explanation: "你好是最基本的問候句，先穩住它。",
      },
      {
        kind: "chooseJyutping",
        id: "a1-01-checkpoint-quiz-2",
        title: "數字回想",
        prompt: "「六」的 Jyutping 係邊個？",
        targetText: "六",
        choices: [
          { id: "luk6", label: "luk6", jyutping: "luk6" },
          { id: "luk1", label: "luk1", jyutping: "luk1" },
          { id: "luk9", label: "luk9", jyutping: "luk9" },
        ],
        correctChoiceId: "luk6",
        explanation: "六是 luk6，這是今天很值得穩住的一個字。",
        glossaryIds: ["g-six"],
      },
      {
        kind: "chooseTone",
        id: "a1-01-checkpoint-quiz-3",
        title: "聲調確認",
        prompt: "「詩」係邊個聲調？",
        syllable: "si",
        correctTone: 1,
        choices: checkpointToneChoices,
        explanation: "第 1 聲先記住，高平音最常拿來做基準。",
        audioId: "audio-tones-si1",
      },
      {
        kind: "fillBlank",
        id: "a1-01-checkpoint-quiz-4",
        title: "問路補空",
        prompt: "補出最自然的一句：",
        template: "請問，廁所___邊度？",
        wordBank: ["喺", "係", "咗", "先"],
        answer: "喺",
        explanation: "喺表示位置，這句是問洗手間最穩妥的句子之一。",
        glossaryIds: ["g-at", "g-bathroom", "g-where"],
      },
      {
        kind: "listenAndChoose",
        id: "a1-01-checkpoint-quiz-5",
        title: "聽字辨音",
        prompt: "你聽到邊個字？",
        audioId: "audio-nei5",
        choices: minimalPairChoices,
        correctChoiceId: "nei5",
        explanation: "你是 nei5，這個 n / l 對比是 A1 很重要的一步。",
        glossaryIds: ["g-hello"],
      },
    ],
  },
] as const satisfies readonly Lesson[];

export const curriculumLessons = [
  ...startHereLessons,
  ...soundLabLessons,
  ...meetAndGreetLessons,
  ...checkpointLessons,
] as const satisfies readonly Lesson[];

export const curriculumSections = [
  {
    id: "start-here",
    order: 1,
    title: "Start Here",
    subtitle: "先把字型、問候與數字熱身起來",
    summary: "這一段先把顯示切換、第一批生存句和最常用數字拉起來。",
    lessonIds: ["start-01-script-toggle", "start-02-survival-phrases", "start-03-numbers-1-10", "start-04-function-words"],
  },
  {
    id: "sound-lab-1",
    order: 2,
    title: "Sound Lab 1",
    subtitle: "先把 Jyutping 與六聲建立起來",
    summary: "這一段專注在拼音、聲調、n / l 和跟讀節奏。",
    lessonIds: ["sound-01-jyutping-basics", "sound-02-six-tones", "sound-03-tone-drill", "sound-04-minimal-pairs"],
  },
  {
    id: "meet-and-greet",
    order: 3,
    title: "Meet & Greet",
    subtitle: "把問路、對話和標示串成實景",
    summary: "這一段開始把場景拉進酒店、前台和公共標示。",
    lessonIds: ["meet-01-bathroom", "meet-02-mini-dialogue", "meet-03-signage-reading"],
  },
  {
    id: "a1-checkpoint",
    order: 4,
    title: "A1 Checkpoint",
    subtitle: "用小測驗確認能往前",
    summary: "這一段只放一份小測驗，幫你快速知道要不要回頭補一輪。",
    lessonIds: ["a1-01-checkpoint-quiz"],
    checkpointLessonId: "a1-01-checkpoint-quiz",
  },
] as const satisfies readonly Section[];
