import type { GlossaryEntry } from "./types";

export const glossaryEntries = [
  {
    id: "g-hello",
    headword: "你好",
    jyutping: "nei5 hou2",
    mandarinGloss: "你好；問候別人時最通用。",
    note: "最穩妥的起手式。",
    audioId: "audio-hello",
    tags: ["問候", "入門"],
  },
  {
    id: "g-please-use",
    headword: "唔該",
    jyutping: "m4 goi1",
    mandarinGloss: "麻煩你；請；謝謝（偏服務場景）。",
    note: "點餐、問路、叫人幫忙都好用。",
    audioId: "audio-m4-goi1",
    tags: ["禮貌", "服務"],
  },
  {
    id: "g-thanks",
    headword: "多謝",
    jyutping: "do1 ze6",
    mandarinGloss: "多謝；謝謝（偏收到幫助或禮物）。",
    note: "收到對方幫忙後常用。",
    audioId: "audio-thanks",
    tags: ["禮貌"],
  },
  {
    id: "g-sorry",
    headword: "對唔住",
    jyutping: "deoi3 m4 zyu6",
    mandarinGloss: "對不起；不好意思。",
    audioId: "audio-sorry",
    tags: ["道歉"],
  },
  {
    id: "g-bye",
    headword: "再見",
    jyutping: "zoi3 gin3",
    mandarinGloss: "再見。",
    audioId: "audio-bye",
    tags: ["告別"],
  },
  {
    id: "g-one",
    headword: "一",
    jyutping: "jat1",
    mandarinGloss: "一。",
    audioId: "audio-one",
    tags: ["數字"],
  },
  {
    id: "g-two",
    headword: "二",
    jyutping: "ji6",
    mandarinGloss: "二。",
    audioId: "audio-two",
    tags: ["數字"],
  },
  {
    id: "g-three",
    headword: "三",
    jyutping: "saam1",
    mandarinGloss: "三。",
    audioId: "audio-three",
    tags: ["數字"],
  },
  {
    id: "g-four",
    headword: "四",
    jyutping: "sei3",
    mandarinGloss: "四。",
    audioId: "audio-four",
    tags: ["數字"],
  },
  {
    id: "g-five",
    headword: "五",
    jyutping: "ng5",
    mandarinGloss: "五。",
    audioId: "audio-five",
    tags: ["數字"],
  },
  {
    id: "g-six",
    headword: "六",
    jyutping: "luk6",
    mandarinGloss: "六。",
    audioId: "audio-six",
    tags: ["數字"],
  },
  {
    id: "g-seven",
    headword: "七",
    jyutping: "cat1",
    mandarinGloss: "七。",
    audioId: "audio-seven",
    tags: ["數字"],
  },
  {
    id: "g-eight",
    headword: "八",
    jyutping: "baat3",
    mandarinGloss: "八。",
    audioId: "audio-eight",
    tags: ["數字"],
  },
  {
    id: "g-nine",
    headword: "九",
    jyutping: "gau2",
    mandarinGloss: "九。",
    audioId: "audio-nine",
    tags: ["數字"],
  },
  {
    id: "g-ten",
    headword: "十",
    jyutping: "sap6",
    mandarinGloss: "十。",
    audioId: "audio-ten",
    tags: ["數字"],
  },
  {
    id: "g-dont",
    headword: "唔",
    jyutping: "m4",
    mandarinGloss: "不；別；沒有。",
    note: "最常見的否定詞之一。",
    audioId: "audio-m4",
    tags: ["語法"],
  },
  {
    id: "g-to-be",
    headword: "係",
    jyutping: "hai6",
    mandarinGloss: "是。",
    note: "口語裡很常見。",
    audioId: "audio-hai6",
    tags: ["語法"],
  },
  {
    id: "g-at",
    headword: "喺",
    jyutping: "hai2",
    mandarinGloss: "在；於。",
    note: "表示位置。",
    audioId: "audio-hai2",
    tags: ["語法", "位置"],
  },
  {
    id: "g-past",
    headword: "咗",
    jyutping: "zo2",
    mandarinGloss: "了；已經完成。",
    note: "表完成。",
    audioId: "audio-zo2",
    tags: ["語法"],
  },
  {
    id: "g-before",
    headword: "先",
    jyutping: "sin1",
    mandarinGloss: "先；才；先做某事。",
    note: "順序和條件都常用。",
    audioId: "audio-sin1",
    tags: ["語法"],
  },
  {
    id: "g-bathroom",
    headword: "廁所",
    jyutping: "ci3 so2",
    mandarinGloss: "廁所；洗手間。",
    audioId: "audio-bathroom",
    tags: ["場所"],
  },
  {
    id: "g-restroom",
    headword: "洗手間",
    jyutping: "sai2 sau2 gaan1",
    mandarinGloss: "洗手間。",
    note: "較委婉、通用。",
    audioId: "audio-washroom",
    tags: ["場所"],
  },
  {
    id: "g-where",
    headword: "邊度",
    jyutping: "bin1 dou6",
    mandarinGloss: "哪裡；哪個位置。",
    audioId: "audio-where",
    tags: ["疑問詞"],
  },
  {
    id: "g-please",
    headword: "請問",
    jyutping: "cing2 man6",
    mandarinGloss: "請問；勞駕請教。",
    audioId: "audio-please-ask",
    tags: ["禮貌"],
  },
  {
    id: "g-checkin",
    headword: "入住登記",
    jyutping: "jap6 zyu6 dang1 gei3",
    mandarinGloss: "入住登記；辦理入住。",
    note: "酒店場景常見。",
    audioId: "audio-checkin",
    tags: ["酒店"],
  },
  {
    id: "g-document",
    headword: "證件",
    jyutping: "zing3 gin6",
    mandarinGloss: "證件；身份文件。",
    audioId: "audio-document",
    tags: ["酒店", "辦事"],
  },
  {
    id: "g-exit",
    headword: "出口",
    jyutping: "ceot1 hau2",
    mandarinGloss: "出口；出口處。",
    audioId: "audio-exit",
    tags: ["標示"],
  },
] as const satisfies readonly GlossaryEntry[];

export type GlossaryId = (typeof glossaryEntries)[number]["id"];

export const glossaryById = glossaryEntries.reduce<Record<GlossaryId, GlossaryEntry>>(
  (result, entry) => {
    result[entry.id] = entry;
    return result;
  },
  {} as Record<GlossaryId, GlossaryEntry>,
);
